# Generated by Django 2.2.4 on 2019-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchentModel',
            fields=[
                ('m_idno', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=30)),
                ('m_contact', models.IntegerField(unique=True)),
                ('m_email', models.EmailField(max_length=254, unique=True)),
                ('m_password', models.CharField(max_length=8)),
            ],
        ),
    ]
