# Generated by Django 2.2.4 on 2019-11-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchentmodel',
            name='m_idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
